version: '3.7'

services:

  flask:
    build:
      context: ./services/weather
      dockerfile: Dockerfile-dev
    volumes:
      - './services/weather:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@weather-db:5432/weather_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@weather-db:5432/weather_test
    depends_on:
      - weather-db

  weather-db:
    build:
      context: ./services/weather/src/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
